global using PizzaXYZ.Backend.Domain.Entities;
global using PizzaXYZ.Backend.Application.Interfaces;
global using PizzaXYZ.Backend.Application.Exceptions;
global using PizzaXYZ.Backend.Application.Services;
global using PizzaXYZ.Backend.Application.Helpers;
global using PizzaXYZ.Backend.Application.Dtos;
global using PizzaXYZ.Backend.Application.Constants;
global using Microsoft.EntityFrameworkCore;
global using MediatR;
